#ifndef APP_CONFIG_H
#define APP_CONFIG_H
#define SAMPLING_STRATEGY_BSDF 0
#define SAMPLING_STRATEGY_SD_TREE 1
#define USE_NEXT_EVENT_ESTIMATION 0
#define SAMPLING_STRATEGY SAMPLING_STRATEGY_SD_TREE
#endif