SAMPLE_UNIFORM = 0
SAMPLE_COSINE = 1
SAMPLE_HG = 1
SAMPLE_Q_PROPORTION = 2
SAMPLE_Q_COS_PROPORTION = 3
SAMPLE_Q_COS_MCMC= 4
SAMPLE_Q_COS_REJECT= 5
SAMPLE_Q_SPHERE=6
SAMPLE_Q_QUADTREE=7
SAMPLE_Q_COS_REJECT_MIX=8

SAMPLE_Q_HG_PROPORTION = 3


Q_UPDATE_EXPECTED_SARSA = 0
#Q_UPDATE_Q_LEARNING = 1
Q_UPDATE_SARSA = 1
Q_UPDATE_SARSA2 = 2
Q_UPDATE_MONTE_CARLO = 3
Q_UPDATE_MONTE_CARLO2 = 4


Q_SAMPLE_PROPORTIONAL_TO_Q = 1
Q_SAMPLE_PROPORTIONAL_TO_Q_SQUARE = 2